name: haskell-sandbox

dependencies:
- base >= 4.7 && < 5
- random
- tasty
- tasty-hunit
- criterion
- scotty

executables:
  eller-maze-exe:
    main: EllerMaze.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  factorial-exe:
    main: Factorial.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  playground-exe:
    main: Playground.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

  simple-http-scotty-exe:
    main: SimpleHttpScotty.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N